version: 2
jobs:
  build:
    filters:
      branches:
        only:
          - twilio_notifier
    docker:
      - image: docker:latest

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Greeting
          command: docker build . -t gui13/twilio_notifier
