version: 2
jobs:
  dev:
    filters:
      branches:
        only:
          - twilio_notifier
    machine: true
    steps:
      - checkout
      - run:
          name: Build & tag as dev
          command: |
            docker build . -t gui13/grafana_twilio:$CIRCLE_SHA1
            docker tag gui13/grafana_twilio:$CIRCLE_SHA1 gui13/grafana_twilio:dev
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push gui13/grafana_twilio:$CIRCLE_SHA1
            docker push gui13/grafana_twilio:dev
  prod:
    machine: true
    filters:
      tags:
        only: /^kdp.*/
    steps:
      - checkout
      - run:
          name:  Tag the dev image as prod
          command: |
            docker pull gui13/grafana_twilio:$CIRCLE_SHA1
            docker tag gui13/grafana_twilio:$CIRCLE_SHA1 gui13/grafana_twilio:latest
            docker tag gui13/grafana_twilio:latest gui13/grafana_twilio:$CIRCLE_TAG
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push gui13/grafana_twilio:latest
            docker push gui13/grafana_twilio:$CIRCLE_TAG


workflows:
  version: 2
  buildprod:
    jobs:
      - dev:
          filters:
            branches:
              only: /^twilio.*/
            tags:
              only: /^kdp.*/
      - prod:
          requires: 
            - dev
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^kdp.*/
